name: Android CI Build APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Compilar (Build) con Gradle para crear la APK de Release
        run: ./gradlew assembleRelease
        # working-directory: Eliminado para buscar en la raíz del repositorio Tcae-sas-cadiz-app

      - name: Subir APK como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-apk-release
          # Ruta de artefacto ajustada a la raíz:
          path: app/build/outputs/apk/release/app-release-unsigned.apk
