name: Android CI Build APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Conceder permisos de ejecución a gradle-wrapper
        run: chmod +x gradlew

      - name: Compilar (Build) con Gradle para crear la APK de Release
        # Reemplaza 'assembleRelease' si usas otro flavor o build type
        run: ./gradlew assembleRelease

      - name: Subir APK como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-apk-release
          # Asegúrate de que esta ruta coincida con la ruta donde Gradle genera la APK
          path: app/build/outputs/apk/release/app-release-unsigned.apk
